name: Lint
on: [pull_request]

jobs:
  lint-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          [
            "coinbase-agentkit",
            "create-onchain-agent",
            "framework-extensions/langchain",
            "framework-extensions/openai-agents-sdk",
            "framework-extensions/strands-agents",
            "examples/langchain-cdp-chatbot",
            "examples/langchain-cdp-solana-chatbot",
            "examples/langchain-cdp-smart-wallet-chatbot",
            "examples/langchain-eth-account-chatbot",
            "examples/langchain-nillion-secretvault-chatbot",
            "examples/langchain-twitter-chatbot",
            "examples/openai-agents-sdk-cdp-chatbot",
            "examples/openai-agents-sdk-cdp-voice-chatbot",
            "examples/openai-agents-sdk-smart-wallet-chatbot",
          ]
    defaults:
      run:
        working-directory: python/${{ matrix.package }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Ensure linting
        run: make lint

  lint-typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"
          cache-dependency-path: ./typescript
      - name: Ensure Linting
        working-directory: ./typescript
        run: |
          pnpm install --frozen-lockfile
          pnpm run lint

  check-package-lock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"
          cache-dependency-path: ./typescript

      - name: Check if pnpm-lock.yaml changed
        working-directory: ./typescript
        run: |
          pnpm install
          if [ -n "$(git diff pnpm-lock.yaml)" ]; then
            echo "Error: pnpm-lock.yaml was modified after running pnpm install. Please commit the updated pnpm-lock.yaml file."
            git diff pnpm-lock.yaml
            exit 1
          fi

  check-uv-locks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Check uv.lock files
        run: |
          for dir in $(find . -name pyproject.toml -exec dirname {} \;); do
            echo "Checking $dir..."
            cd $dir
            uv sync
            if [ -n "$(git diff uv.lock)" ]; then
              echo "Error: uv.lock in $dir was modified after running uv sync. Please commit the updated uv.lock file."
              git diff uv.lock
              exit 1
            fi
            cd - > /dev/null
          done
