name: Run Unit Tests
on: [pull_request]

jobs:
  test-coinbase-agentkit-python:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python/coinbase-agentkit
    strategy:
      matrix:
        python: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Run tests
        run: make test

  test-agentkit-typescript:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["18", "20"]
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: ./typescript

      - name: Install and test AgentKit.js
        working-directory: ./typescript
        run: |
          pnpm install --frozen-lockfile
          pnpm run test
